In [1]:
import pandas as pd

In [6]:
pop= {
    'California': 38332521,
    'Texas': 26448193,
    'New York': 19651127,
    'Florida': 19552860,
    'Illinois': 12882135}
area = {
    'California': 38521,
    'Texas': 26493,
    'New York': 11127,
    'Florida': 1950,
    'Illinois': 91135
}
df = pd.DataFrame({'Population': pop, 'Area': area})
df

            Population   Area
California    38332521  38521
Texas         26448193  26493
New York      19651127  11127
Florida       19552860   1950
Illinois      12882135  91135

In [7]:
df1 = pd.DataFrame({'Name': ['Ali', 'Sara', 'Sarim', 'Kareem'],
                  'Age' : [23,22, 32,45],
                  'Id' : [111, 123,143,154]
                  })
df1

     Name  Age   Id
0     Ali   23  111
1    Sara   22  123
2   Sarim   32  143
3  Kareem   45  154

In [9]:
print(df.index)
print(df1.index)

Index(['California', 'Texas', 'New York', 'Florida', 'Illinois'], dtype='object')
RangeIndex(start=0, stop=4, step=1)

In [10]:
print(df.columns)
print(df1.columns)

Index(['Population', 'Area'], dtype='object')
Index(['Name', 'Age', 'Id'], dtype='object')

In [11]:
df['Area']

California    38521
Texas         26493
New York      11127
Florida        1950
Illinois      91135
Name: Area, dtype: int64

In [12]:
df1['Age']

0    23
1    22
2    32
3    45
Name: Age, dtype: int64

In [13]:
data = {
    'Name': ['Ali', 'Sara', 'Sarim', 'Kareem'],
    'Age' : [23,22, 32,45],
     'Maths' : [89, 87,98,88],
    'Physics': [87, 56,77,89],
    'Chemistry': [85, 67,74,65]
                  }
student = pd.DataFrame(data)
student

     Name  Age  Maths  Physics  Chemistry
0     Ali   23     89       87         85
1    Sara   22     87       56         67
2   Sarim   32     98       77         74
3  Kareem   45     88       89         65

In [14]:
student[['Name', 'Chemistry']]

     Name  Chemistry
0     Ali         85
1    Sara         67
2   Sarim         74
3  Kareem         65

In [15]:
student['Age'] = [23,22,21,20]
student

     Name  Age  Maths  Physics  Chemistry
0     Ali   23     89       87         85
1    Sara   22     87       56         67
2   Sarim   21     98       77         74
3  Kareem   20     88       89         65

## Adding new column

In [16]:
student['Python'] = [78,82,84,91]
student

     Name  Age  Maths  Physics  Chemistry  Python
0     Ali   23     89       87         85      78
1    Sara   22     87       56         67      82
2   Sarim   21     98       77         74      84
3  Kareem   20     88       89         65      91

In [17]:
student['Total Marks'] = student[['Maths', 'Physics', 'Chemistry', 'Python']].sum(axis=1)
student

     Name  Age  Maths  Physics  Chemistry  Python  Total Marks
0     Ali   23     89       87         85      78          339
1    Sara   22     87       56         67      82          292
2   Sarim   21     98       77         74      84          333
3  Kareem   20     88       89         65      91          333

In [18]:
student['Percentage'] = (student['Total Marks']/400) *100

In [ ]:
student['Percentage'] = student['Total Marks'].apply(lambda x: (x/400) *100 )

In [19]:
student

     Name  Age  Maths  Physics  Chemistry  Python  Total Marks  Percentage
0     Ali   23     89       87         85      78          339       84.75
1    Sara   22     87       56         67      82          292       73.00
2   Sarim   21     98       77         74      84          333       83.25
3  Kareem   20     88       89         65      91          333       83.25

In [20]:
student['Grade'] = student['Percentage'].apply(lambda x: 
                                             'A1' if x>=85 else 
                                            'A' if x>=80 else
                                             'B'  if x>=70 else
                                              'c'  if x>=60 else 'D')
student

,Name,Age,Maths,Physics,Chemistry,Python,Total Marks,Percentage,Grade
0,Ali,23,89,87,85,78,339,84.75,A
1,Sara,22,87,56,67,82,292,73.00,B
2,Sarim,21,98,77,74,84,333,83.25,A
3,Kareem,20,88,89,65,91,333,83.25,A

In [21]:
student['Python'] = student['Python'] + 2 
student

,Name,Age,Maths,Physics,Chemistry,Python,Total Marks,Percentage,Grade
0,Ali,23,89,87,85,80,339,84.75,A
1,Sara,22,87,56,67,84,292,73.00,B
2,Sarim,21,98,77,74,86,333,83.25,A
3,Kareem,20,88,89,65,93,333,83.25,A

In [22]:
data = pd.Series([0.25, 0.5, 0.75, 1.0], index=['a', 'b', 'c', 'd'])
data

a    0.25
b    0.50
c    0.75
d    1.00
dtype: float64

In [23]:
data['a':'c']

a    0.25
b    0.50
c    0.75
dtype: float64

In [24]:
data[1:3] # implicit index

b    0.50
c    0.75
dtype: float64

In [26]:
data.loc['a']

0.25

In [27]:
data.iloc[1]

0.5

In [28]:
data.loc['b':'d']

b    0.50
c    0.75
d    1.00
dtype: float64

In [29]:
data.iloc[1:]

b    0.50
c    0.75
d    1.00
dtype: float64

In [30]:
student

,Name,Age,Maths,Physics,Chemistry,Python,Total Marks,Percentage,Grade
0,Ali,23,89,87,85,80,339,84.75,A
1,Sara,22,87,56,67,84,292,73.00,B
2,Sarim,21,98,77,74,86,333,83.25,A
3,Kareem,20,88,89,65,93,333,83.25,A

In [33]:
student.loc[:, ['Age', 'Maths', 'Physics']]

   Age  Maths  Physics
0   23     89       87
1   22     87       56
2   21     98       77
3   20     88       89

In [34]:
student.iloc[: ,1:4 ]

   Age  Maths  Physics
0   23     89       87
1   22     87       56
2   21     98       77
3   20     88       89

In [35]:
student['Maths']

0    89
1    87
2    98
3    88
Name: Maths, dtype: int64

In [36]:
student.Maths

0    89
1    87
2    98
3    88
Name: Maths, dtype: int64

In [37]:
df

            Population   Area
California    38332521  38521
Texas         26448193  26493
New York      19651127  11127
Florida       19552860   1950
Illinois      12882135  91135

In [38]:
df.values

array([[38332521,    38521],
       [26448193,    26493],
       [19651127,    11127],
       [19552860,     1950],
       [12882135,    91135]], dtype=int64)

In [39]:
df.T

            California     Texas  New York   Florida  Illinois
Population    38332521  26448193  19651127  19552860  12882135
Area             38521     26493     11127      1950     91135

In [40]:
student

,Name,Age,Maths,Physics,Chemistry,Python,Total Marks,Percentage,Grade
0,Ali,23,89,87,85,80,339,84.75,A
1,Sara,22,87,56,67,84,292,73.00,B
2,Sarim,21,98,77,74,86,333,83.25,A
3,Kareem,20,88,89,65,93,333,83.25,A

In [42]:
student['Python'] > 80

0    False
1     True
2     True
3     True
Name: Python, dtype: bool

In [43]:
student[student['Python'] > 80]

,Name,Age,Maths,Physics,Chemistry,Python,Total Marks,Percentage,Grade
1,Sara,22,87,56,67,84,292,73.00,B
2,Sarim,21,98,77,74,86,333,83.25,A
3,Kareem,20,88,89,65,93,333,83.25,A

In [44]:
student[student['Maths']>90]

,Name,Age,Maths,Physics,Chemistry,Python,Total Marks,Percentage,Grade
2,Sarim,21,98,77,74,86,333,83.25,A

In [45]:
student[student['Percentage'] > 75]

,Name,Age,Maths,Physics,Chemistry,Python,Total Marks,Percentage,Grade
0,Ali,23,89,87,85,80,339,84.75,A
2,Sarim,21,98,77,74,86,333,83.25,A
3,Kareem,20,88,89,65,93,333,83.25,A

In [48]:
student[(student['Maths'] > 80) & (student['Python'] > 80)]

,Name,Age,Maths,Physics,Chemistry,Python,Total Marks,Percentage,Grade
1,Sara,22,87,56,67,84,292,73.00,B
2,Sarim,21,98,77,74,86,333,83.25,A
3,Kareem,20,88,89,65,93,333,83.25,A

In [52]:
import numpy as np
A = pd.DataFrame(np.arange(1,5).reshape(2, 2), columns=list('AB'))

In [54]:
 B = pd.DataFrame(np.random.randint(0, 10, (3, 3)), columns=list('BAC'))

In [55]:
B

   B  A  C
0  2  3  0
1  0  6  4
2  8  7  1

In [53]:
A

   A  B
0  1  2
1  3  4

In [57]:
C = A + B

In [58]:
C

     A    B   C
0  4.0  4.0 NaN
1  9.0  4.0 NaN
2  NaN  NaN NaN