In [1]:
import pandas as pd

In [6]:
df1 = pd.DataFrame({'A': ['A1', 'A2'], 'B': ['B1','B2']}, index=[0,1] )
df2 = pd.DataFrame({'A': ['A3', 'A4'], 'B': ['B3','B4']}, index=[3,4])
print(df1); print(df2)

    A   B
0  A1  B1
1  A2  B2
    A   B
3  A3  B3
4  A4  B4

In [7]:
print(pd.concat([df1, df2]))

    A   B
0  A1  B1
1  A2  B2
3  A3  B3
4  A4  B4

In [9]:
print(pd.concat([df1, df2], axis=1))

     A    B    A    B
0   A1   B1  NaN  NaN
1   A2   B2  NaN  NaN
3  NaN  NaN   A3   B3
4  NaN  NaN   A4   B4

In [11]:
df3 = pd.DataFrame({'A': ['A1', 'A2'], 'B': ['B1','B2']}, index=[0,1] )
df4 = pd.DataFrame({'A': ['A3', 'A4'], 'B': ['B3','B4']}, index=[0,1])
print(df3); print(df4)

    A   B
0  A1  B1
1  A2  B2
    A   B
0  A3  B3
1  A4  B4

In [13]:
print(pd.concat([df3, df4], axis=1 ))

    A   B   A   B
0  A1  B1  A3  B3
1  A2  B2  A4  B4

In [14]:
print(pd.concat([df3, df4], axis=0 ))

    A   B
0  A1  B1
1  A2  B2
0  A3  B3
1  A4  B4

In [15]:
print(pd.concat([df3, df4], axis=0 ,  ignore_index=True))

    A   B
0  A1  B1
1  A2  B2
2  A3  B3
3  A4  B4

In [18]:
print(pd.concat([df3, df4], axis=0 , keys=['x', 'y']))

      A   B
x 0  A1  B1
  1  A2  B2
y 0  A3  B3
  1  A4  B4

In [19]:
df3 = pd.DataFrame({'A': ['A1', 'A2'], 'B': ['B1','B2'], 'C': ['C1','C2']}, index=[1,2] )
df4 = pd.DataFrame({'B': ['B3','B4'], 'C': ['C1','C2'],'D': ['D3', 'D4']}, index=[3,4])
print(df3); print(df4)

    A   B   C
1  A1  B1  C1
2  A2  B2  C2
    B   C   D
3  B3  C1  D3
4  B4  C2  D4

In [20]:
print(pd.concat([df3, df4]))

     A   B   C    D
1   A1  B1  C1  NaN
2   A2  B2  C2  NaN
3  NaN  B3  C1   D3
4  NaN  B4  C2   D4

In [22]:
print(pd.concat([df3, df4], join='inner'))

    B   C
1  B1  C1
2  B2  C2
3  B3  C1
4  B4  C2

# Combining Datasets: Merge and Join

In [25]:
df1 = pd.DataFrame(
    {
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"], },  index=[0, 1, 2, 3],)
df2 = pd.DataFrame(
    {
        "A": ["A4", "A5", "A6", "A7"],
        "B": ["B4", "B5", "B6", "B7"],
        "C": ["C4", "C5", "C6", "C7"],
        "D": ["D4", "D5", "D6", "D7"],}, index=[4, 5, 6, 7],)
df3 = pd.DataFrame(
    {
        "A": ["A8", "A9", "A10", "A11"],
        "B": ["B8", "B9", "B10", "B11"],
        "C": ["C8", "C9", "C10", "C11"],
        "D": ["D8", "D9", "D10", "D11"], }, index=[8, 9, 10, 11],)

In [26]:
df1

    A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3

In [27]:
df2

    A   B   C   D
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7  B7  C7  D7

In [28]:
df3

      A    B    C    D
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [29]:
pd.concat([df1, df2, df3])

      A    B    C    D
0    A0   B0   C0   D0
1    A1   B1   C1   D1
2    A2   B2   C2   D2
3    A3   B3   C3   D3
4    A4   B4   C4   D4
5    A5   B5   C5   D5
6    A6   B6   C6   D6
7    A7   B7   C7   D7
8    A8   B8   C8   D8
9    A9   B9   C9   D9
10  A10  B10  C10  D10
11  A11  B11  C11  D11

In [30]:
df4 = pd.DataFrame(
    {
        "B": ["B2", "B3", "B6", "B7"],
        "D": ["D2", "D3", "D6", "D7"],
        "F": ["F2", "F3", "F6", "F7"],
    },index=[2, 3, 6, 7],)
df4

    B   D   F
2  B2  D2  F2
3  B3  D3  F3
6  B6  D6  F6
7  B7  D7  F7

In [31]:
 pd.concat([df1, df4], axis=1)

     A    B    C    D    B    D    F
0   A0   B0   C0   D0  NaN  NaN  NaN
1   A1   B1   C1   D1  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3
6  NaN  NaN  NaN  NaN   B6   D6   F6
7  NaN  NaN  NaN  NaN   B7   D7   F7

In [32]:
 pd.concat([df1, df4], axis=1, join="inner")

    A   B   C   D   B   D   F
2  A2  B2  C2  D2  B2  D2  F2
3  A3  B3  C3  D3  B3  D3  F3

In [34]:
 pd.concat([df1, df4], axis=0, join="inner", ignore_index=True)

    B   D
0  B0  D0
1  B1  D1
2  B2  D2
3  B3  D3
4  B2  D2
5  B3  D3
6  B6  D6
7  B7  D7

In [37]:
 pd.concat([df1, df4], axis=1, join="inner").reindex(df1.index)

     A    B    C    D    B    D    F
0  NaN  NaN  NaN  NaN  NaN  NaN  NaN
1  NaN  NaN  NaN  NaN  NaN  NaN  NaN
2   A2   B2   C2   D2   B2   D2   F2
3   A3   B3   C3   D3   B3   D3   F3

In [39]:
d= pd.concat([df1, df4, df2],  keys=["x", "y", "z"])

In [40]:
d

       A   B    C   D    F
x 0   A0  B0   C0  D0  NaN
  1   A1  B1   C1  D1  NaN
  2   A2  B2   C2  D2  NaN
  3   A3  B3   C3  D3  NaN
y 2  NaN  B2  NaN  D2   F2
  3  NaN  B3  NaN  D3   F3
  6  NaN  B6  NaN  D6   F6
  7  NaN  B7  NaN  D7   F7
z 4   A4  B4   C4  D4  NaN
  5   A5  B5   C5  D5  NaN
  6   A6  B6   C6  D6  NaN
  7   A7  B7   C7  D7  NaN

In [41]:
d.loc["y"]

     A   B    C   D   F
2  NaN  B2  NaN  D2  F2
3  NaN  B3  NaN  D3  F3
6  NaN  B6  NaN  D6  F6
7  NaN  B7  NaN  D7  F7

In [43]:
 pd.concat([df1, df4], axis=0, join="outer")

     A   B    C   D    F
0   A0  B0   C0  D0  NaN
1   A1  B1   C1  D1  NaN
2   A2  B2   C2  D2  NaN
3   A3  B3   C3  D3  NaN
2  NaN  B2  NaN  D2   F2
3  NaN  B3  NaN  D3   F3
6  NaN  B6  NaN  D6   F6
7  NaN  B7  NaN  D7   F7

In [52]:
left = pd.DataFrame({
        "key": ["K0", "K1", "K2", "K3"],
        "A": ["A0", "A1", "A2", "A3"],
        "B": ["B0", "B1", "B2", "B3"], })
right = pd.DataFrame( {
        "key": ["K0", "K1", "K2", "K3"],
        "C": ["C0", "C1", "C2", "C3"],
        "D": ["D0", "D1", "D2", "D3"],})

In [57]:
print(left); right

  key   A   B
0  K0  A0  B0
1  K1  A1  B1
2  K2  A2  B2
3  K3  A3  B3

  key   C   D
0  K0  C0  D0
1  K1  C1  D1
2  K2  C2  D2
3  K3  C3  D3

In [55]:
 pd.concat([left, right])

  key    A    B    C    D
0  K0   A0   B0  NaN  NaN
1  K1   A1   B1  NaN  NaN
2  K2   A2   B2  NaN  NaN
3  K3   A3   B3  NaN  NaN
0  K0  NaN  NaN   C0   D0
1  K1  NaN  NaN   C1   D1
2  K2  NaN  NaN   C2   D2
3  K3  NaN  NaN   C3   D3

In [56]:
pd.merge(left, right, on="key")

  key   A   B   C   D
0  K0  A0  B0  C0  D0
1  K1  A1  B1  C1  D1
2  K2  A2  B2  C2  D2
3  K3  A3  B3  C3  D3

In [58]:
left = pd.DataFrame({
      "key1": ["K0", "K0", "K1", "K2"],
      "key2": ["K0", "K1", "K0", "K1"],
      "A": ["A0", "A1", "A2", "A3"],
      "B": ["B0", "B1", "B2", "B3"], })
right = pd.DataFrame( {
      "key1": ["K0", "K1", "K1", "K2"],
      "key2": ["K0", "K0", "K0", "K0"],
      "C": ["C0", "C1", "C2", "C3"],
      "D": ["D0", "D1", "D2", "D3"],})

In [59]:
pd.merge(left, right, how="left", on=["key1", "key2"])

  key1 key2   A   B    C    D
0   K0   K0  A0  B0   C0   D0
1   K0   K1  A1  B1  NaN  NaN
2   K1   K0  A2  B2   C1   D1
3   K1   K0  A2  B2   C2   D2
4   K2   K1  A3  B3  NaN  NaN