In [1]:
import pandas as pd

In [3]:
df1 = pd.DataFrame({'employee': ['Bob', 'Jake', 'Lisa', 'Sue'],
                    'group': ['Accounting', 'Engineering', 'Engineering', 'HR']
                   })

df2 = pd.DataFrame({'employee': ['Lisa', 'Bob', 'Jake', 'Sue'],
                    'hire_date': [2004, 2008, 2012, 2014]
                   })
print(df1); print(df2)
pd.merge(df1, df2)

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR
  employee  hire_date
0     Lisa       2004
1      Bob       2008
2     Jake       2012
3      Sue       2014

  employee        group  hire_date
0      Bob   Accounting       2008
1     Jake  Engineering       2012
2     Lisa  Engineering       2004
3      Sue           HR       2014

In [7]:
df3 = pd.merge(df1, df2)
df4 = pd.DataFrame({'group': ['Accounting', 'Engineering', 'HR'],
                    'supervisor': ['Carly', 'Guido', 'Steve']})

In [6]:
pd.merge(df3, df4)

  employee        group  hire_date supervisor
0      Bob   Accounting       2008      Carly
1     Jake  Engineering       2012      Guido
2     Lisa  Engineering       2004      Guido
3      Sue           HR       2014      Steve

In [10]:
df5 = pd.DataFrame({
    'group': ['Accounting', 'Accounting','Engineering', 'Engineering', 'HR', 'HR'],
    'skills': ['math', 'spreadsheets', 'coding', 'linux','spreadsheets', 'organization']
})

In [13]:
df1

  employee        group
0      Bob   Accounting
1     Jake  Engineering
2     Lisa  Engineering
3      Sue           HR

In [12]:
df5

         group        skills
0   Accounting          math
1   Accounting  spreadsheets
2  Engineering        coding
3  Engineering         linux
4           HR  spreadsheets
5           HR  organization

In [16]:
pd.merge(df1, df5, on='group')

  employee        group        skills
0      Bob   Accounting          math
1      Bob   Accounting  spreadsheets
2     Jake  Engineering        coding
3     Jake  Engineering         linux
4     Lisa  Engineering        coding
5     Lisa  Engineering         linux
6      Sue           HR  spreadsheets
7      Sue           HR  organization

In [17]:
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-population.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
 11 57935   11  6890    0     0   9925      0  0:00:05 --:--:--  0:00:05  9956
100 57935  100 57935    0     0  75644      0 --:--:-- --:--:-- --:--:-- 75831

In [18]:
!curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-areas.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   835  100   835    0     0   1796      0 --:--:-- --:--:-- --:--:--  1807
100   835  100   835    0     0   1794      0 --:--:-- --:--:-- --:--:--  1803

In [19]:
 !curl -O https://raw.githubusercontent.com/jakevdp/data-USstates/master/state-abbrevs.csv

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100   872  100   872    0     0   1288      0 --:--:-- --:--:-- --:--:--  1293
100   872  100   872    0     0   1287      0 --:--:-- --:--:-- --:--:--  1291

In [20]:
pop = pd.read_csv('state-population.csv')
pop.head(3)

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0

In [23]:
pop.shape

(2544, 4)

In [24]:
pop.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2544 entries, 0 to 2543
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   state/region  2544 non-null   object
 1   ages          2544 non-null   object
 2   year          2544 non-null   int64
 3   population    2524 non-null   float64
dtypes: float64(1), int64(1), object(2)
memory usage: 79.6+ KB

In [25]:
pop.isnull().sum()

state/region     0
ages             0
year             0
population      20
dtype: int64

In [21]:
areas = pd.read_csv('state-areas.csv')
areas.head(3)

     state  area (sq. mi)
0  Alabama          52423
1   Alaska         656425
2  Arizona         114006

In [22]:
abbrevs = pd.read_csv('state-abbrevs.csv')
abbrevs.head(3)

     state abbreviation
0  Alabama           AL
1   Alaska           AK
2  Arizona           AZ

In [26]:
pop.head(3)

  state/region     ages  year  population
0           AL  under18  2012   1117489.0
1           AL    total  2012   4817528.0
2           AL  under18  2010   1130966.0

In [41]:
pop['state/region'].unique()

array(['AL', 'AK', 'AZ', 'AR', 'CA', 'CO', 'CT', 'DE', 'DC', 'FL', 'GA',
       'HI', 'ID', 'IL', 'IN', 'IA', 'KS', 'KY', 'LA', 'ME', 'MD', 'MA',
       'MI', 'MN', 'MS', 'MO', 'MT', 'NE', 'NV', 'NH', 'NJ', 'NM', 'NY',
       'NC', 'ND', 'OH', 'OK', 'OR', 'PA', 'RI', 'SC', 'SD', 'TN', 'TX',
       'UT', 'VT', 'VA', 'WA', 'WV', 'WI', 'WY', 'PR', 'USA'],
      dtype=object)

In [42]:
pop['state/region'].value_counts().count()

state/region
AL     48
NE     48
NH     48
NJ     48
NM     48
NY     48
NC     48
ND     48
OH     48
OK     48
OR     48
PA     48
RI     48
SC     48
SD     48
TN     48
TX     48
UT     48
VT     48
VA     48
WA     48
WV     48
WI     48
WY     48
PR     48
NV     48
MT     48
AK     48
MO     48
AZ     48
AR     48
CA     48
CO     48
CT     48
DE     48
DC     48
FL     48
GA     48
HI     48
ID     48
IL     48
IN     48
IA     48
KS     48
KY     48
LA     48
ME     48
MD     48
MA     48
MI     48
MN     48
MS     48
USA    48
Name: count, dtype: int64

In [27]:
merged = pd.merge(pop, abbrevs, how='outer',left_on='state/region',
                  right_on='abbreviation')
merged

     state/region     ages  year  population    state abbreviation
0              AK    total  1990    553290.0   Alaska           AK
1              AK  under18  1990    177502.0   Alaska           AK
2              AK    total  1992    588736.0   Alaska           AK
3              AK  under18  1991    182180.0   Alaska           AK
4              AK  under18  1992    184878.0   Alaska           AK
...           ...      ...   ...         ...      ...          ...
2539           WY  under18  1993    137458.0  Wyoming           WY
2540           WY    total  1991    459260.0  Wyoming           WY
2541           WY  under18  1991    136720.0  Wyoming           WY
2542           WY  under18  1990    136078.0  Wyoming           WY
2543           WY    total  1990    453690.0  Wyoming           WY

[2544 rows x 6 columns]

In [30]:
merged.drop('abbreviation', axis=1, inplace=True)
merged

     state/region     ages  year  population    state
0              AK    total  1990    553290.0   Alaska
1              AK  under18  1990    177502.0   Alaska
2              AK    total  1992    588736.0   Alaska
3              AK  under18  1991    182180.0   Alaska
4              AK  under18  1992    184878.0   Alaska
...           ...      ...   ...         ...      ...
2539           WY  under18  1993    137458.0  Wyoming
2540           WY    total  1991    459260.0  Wyoming
2541           WY  under18  1991    136720.0  Wyoming
2542           WY  under18  1990    136078.0  Wyoming
2543           WY    total  1990    453690.0  Wyoming

[2544 rows x 5 columns]

In [31]:
 merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state            True
dtype: bool

In [32]:
 merged.isnull().sum()

state/region     0
ages             0
year             0
population      20
state           96
dtype: int64

In [33]:
merged.shape

(2544, 5)

In [43]:
 merged.loc[merged['state'].isnull(), 'state/region'].unique()

array(['PR', 'USA'], dtype=object)

In [44]:
merged.loc[merged['state/region'] == 'PR', 'state'] = 'Puerto Rico'
merged.loc[merged['state/region'] == 'USA', 'state'] = 'United States'
merged.isnull().any()

state/region    False
ages            False
year            False
population       True
state           False
dtype: bool

In [45]:
merged.head()

  state/region     ages  year  population   state
0           AK    total  1990    553290.0  Alaska
1           AK  under18  1990    177502.0  Alaska
2           AK    total  1992    588736.0  Alaska
3           AK  under18  1991    182180.0  Alaska
4           AK  under18  1992    184878.0  Alaska

In [46]:
areas.head(3)

     state  area (sq. mi)
0  Alabama          52423
1   Alaska         656425
2  Arizona         114006

In [47]:
final = pd.merge(merged, areas, on='state', how='left')
final.head()

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0
3           AK  under18  1991    182180.0  Alaska       656425.0
4           AK  under18  1992    184878.0  Alaska       656425.0

In [48]:
final.isnull().sum()

state/region      0
ages              0
year              0
population       20
state             0
area (sq. mi)    48
dtype: int64

In [50]:
final[final['population'].isnull()==True]

     state/region     ages  year  population        state  area (sq. mi)
1872           PR  under18  1990         NaN  Puerto Rico         3515.0
1873           PR    total  1990         NaN  Puerto Rico         3515.0
1874           PR    total  1991         NaN  Puerto Rico         3515.0
1875           PR  under18  1991         NaN  Puerto Rico         3515.0
1876           PR    total  1993         NaN  Puerto Rico         3515.0
1877           PR  under18  1993         NaN  Puerto Rico         3515.0
1878           PR  under18  1992         NaN  Puerto Rico         3515.0
1879           PR    total  1992         NaN  Puerto Rico         3515.0
1880           PR  under18  1994         NaN  Puerto Rico         3515.0
1881           PR    total  1994         NaN  Puerto Rico         3515.0
1882           PR    total  1995         NaN  Puerto Rico         3515.0
1883           PR  under18  1995         NaN  Puerto Rico         3515.0
1884           PR  under18  1996         NaN  Puerto Rico         3515.0
1885           PR    total  1996         NaN  Puerto Rico         3515.0
1886           PR  under18  1998         NaN  Puerto Rico         3515.0
1887           PR    total  1998         NaN  Puerto Rico         3515.0
1888           PR    total  1997         NaN  Puerto Rico         3515.0
1889           PR  under18  1997         NaN  Puerto Rico         3515.0
1890           PR    total  1999         NaN  Puerto Rico         3515.0
1891           PR  under18  1999         NaN  Puerto Rico         3515.0

In [51]:
final[(final['state/region'] == 'PR') & (final['population'].isnull() == False)]

     state/region     ages  year  population        state  area (sq. mi)
1892           PR    total  2000   3810605.0  Puerto Rico         3515.0
1893           PR  under18  2000   1089063.0  Puerto Rico         3515.0
1894           PR    total  2001   3818774.0  Puerto Rico         3515.0
1895           PR  under18  2001   1077566.0  Puerto Rico         3515.0
1896           PR    total  2002   3823701.0  Puerto Rico         3515.0
1897           PR  under18  2002   1065051.0  Puerto Rico         3515.0
1898           PR    total  2004   3826878.0  Puerto Rico         3515.0
1899           PR  under18  2004   1035919.0  Puerto Rico         3515.0
1900           PR    total  2003   3826095.0  Puerto Rico         3515.0
1901           PR  under18  2003   1050615.0  Puerto Rico         3515.0
1902           PR    total  2005   3821362.0  Puerto Rico         3515.0
1903           PR  under18  2005   1019447.0  Puerto Rico         3515.0
1904           PR    total  2006   3805214.0  Puerto Rico         3515.0
1905           PR  under18  2006    998543.0  Puerto Rico         3515.0
1906           PR    total  2007   3782995.0  Puerto Rico         3515.0
1907           PR  under18  2007    973613.0  Puerto Rico         3515.0
1908           PR    total  2008   3760866.0  Puerto Rico         3515.0
1909           PR  under18  2008    945705.0  Puerto Rico         3515.0
1910           PR  under18  2013    814068.0  Puerto Rico         3515.0
1911           PR    total  2013   3615086.0  Puerto Rico         3515.0
1912           PR    total  2009   3740410.0  Puerto Rico         3515.0
1913           PR  under18  2009    920794.0  Puerto Rico         3515.0
1914           PR    total  2010   3721208.0  Puerto Rico         3515.0
1915           PR  under18  2010    896945.0  Puerto Rico         3515.0
1916           PR  under18  2011    869327.0  Puerto Rico         3515.0
1917           PR    total  2011   3686580.0  Puerto Rico         3515.0
1918           PR  under18  2012    841740.0  Puerto Rico         3515.0
1919           PR    total  2012   3651545.0  Puerto Rico         3515.0

In [52]:
final['state'][final['area (sq. mi)'].isnull()].unique()

array(['United States'], dtype=object)

In [54]:
final[final['area (sq. mi)'].isnull()]

     state/region     ages  year   population          state  area (sq. mi)
2160          USA  under18  1990   64218512.0  United States            NaN
2161          USA    total  1990  249622814.0  United States            NaN
2162          USA    total  1991  252980942.0  United States            NaN
2163          USA  under18  1991   65313018.0  United States            NaN
2164          USA  under18  1992   66509177.0  United States            NaN
2165          USA    total  1992  256514231.0  United States            NaN
2166          USA    total  1993  259918595.0  United States            NaN
2167          USA  under18  1993   67594938.0  United States            NaN
2168          USA  under18  1994   68640936.0  United States            NaN
2169          USA    total  1994  263125826.0  United States            NaN
2170          USA  under18  1995   69473140.0  United States            NaN
2171          USA  under18  1996   70233512.0  United States            NaN
2172          USA    total  1995  266278403.0  United States            NaN
2173          USA    total  1996  269394291.0  United States            NaN
2174          USA    total  1997  272646932.0  United States            NaN
2175          USA  under18  1997   70920738.0  United States            NaN
2176          USA  under18  1998   71431406.0  United States            NaN
2177          USA    total  1998  275854116.0  United States            NaN
2178          USA  under18  1999   71946051.0  United States            NaN
2179          USA    total  2000  282162411.0  United States            NaN
2180          USA  under18  2000   72376189.0  United States            NaN
2181          USA    total  1999  279040181.0  United States            NaN
2182          USA    total  2001  284968955.0  United States            NaN
2183          USA  under18  2001   72671175.0  United States            NaN
2184          USA    total  2002  287625193.0  United States            NaN
2185          USA  under18  2002   72936457.0  United States            NaN
2186          USA    total  2003  290107933.0  United States            NaN
2187          USA  under18  2003   73100758.0  United States            NaN
2188          USA    total  2004  292805298.0  United States            NaN
2189          USA  under18  2004   73297735.0  United States            NaN
2190          USA    total  2005  295516599.0  United States            NaN
2191          USA  under18  2005   73523669.0  United States            NaN
2192          USA    total  2006  298379912.0  United States            NaN
2193          USA  under18  2006   73757714.0  United States            NaN
2194          USA    total  2007  301231207.0  United States            NaN
2195          USA  under18  2007   74019405.0  United States            NaN
2196          USA    total  2008  304093966.0  United States            NaN
2197          USA  under18  2008   74104602.0  United States            NaN
2198          USA  under18  2013   73585872.0  United States            NaN
2199          USA    total  2013  316128839.0  United States            NaN
2200          USA    total  2009  306771529.0  United States            NaN
2201          USA  under18  2009   74134167.0  United States            NaN
2202          USA  under18  2010   74119556.0  United States            NaN
2203          USA    total  2010  309326295.0  United States            NaN
2204          USA  under18  2011   73902222.0  United States            NaN
2205          USA    total  2011  311582564.0  United States            NaN
2206          USA  under18  2012   73708179.0  United States            NaN
2207          USA    total  2012  313873685.0  United States            NaN

In [55]:
final[(final['state/region'] =='USA' )  &
(final['area (sq. mi)'].isnull() == False)]

Empty DataFrame
Columns: [state/region, ages, year, population, state, area (sq. mi)]
Index: []

In [56]:
final.dropna(inplace=True)
final.head(3)

  state/region     ages  year  population   state  area (sq. mi)
0           AK    total  1990    553290.0  Alaska       656425.0
1           AK  under18  1990    177502.0  Alaska       656425.0
2           AK    total  1992    588736.0  Alaska       656425.0

In [58]:
final.query("year == 2010 & ages == 'total'").head()

    state/region   ages  year  population       state  area (sq. mi)
43            AK  total  2010    713868.0      Alaska       656425.0
51            AL  total  2010   4785570.0     Alabama        52423.0
141           AR  total  2010   2922280.0    Arkansas        53182.0
149           AZ  total  2010   6408790.0     Arizona       114006.0
197           CA  total  2010  37333601.0  California       163707.0

In [59]:
final[(final['year']==2010 ) & (final['ages'] == 'total')].head()

    state/region   ages  year  population       state  area (sq. mi)
43            AK  total  2010    713868.0      Alaska       656425.0
51            AL  total  2010   4785570.0     Alabama        52423.0
141           AR  total  2010   2922280.0    Arkansas        53182.0
149           AZ  total  2010   6408790.0     Arizona       114006.0
197           CA  total  2010  37333601.0  California       163707.0