In [21]:
import pandas as pd

In [22]:
df = pd.read_csv(r"sales_data.csv")

# Basic Information and Overview

## Show first and last rows

In [23]:

print(df.head(3))

         date     product     category   price  quantity  revenue
0  2022-01-01  Smartphone  Electronics   600.0      10.0   6000.0
1  2022-01-01      Laptop  Electronics  1200.0       5.0   6000.0
2  2022-01-02     T-Shirt     Clothing    20.0      50.0   1000.0

In [24]:
df.tail(3)

           date     product     category  price  quantity  revenue
366  2022-12-29  Headphones  Electronics  100.0      10.0   1000.0
367  2022-12-30  Smartphone  Electronics  600.0      11.0   6600.0
368  2022-12-31      Hoodie     Clothing   40.0      30.0   1200.0

### Summary info

In [25]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 369 entries, 0 to 368
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   date      369 non-null    object
 1   product   369 non-null    object
 2   category  369 non-null    object
 3   price     367 non-null    float64
 4   quantity  368 non-null    float64
 5   revenue   368 non-null    float64
dtypes: float64(3), object(3)
memory usage: 17.4+ KB
None

## Basic stats for numerical columns

In [26]:
print(df.describe())

             price    quantity      revenue
count   367.000000  368.000000   368.000000
mean    211.226158   14.565217  2060.679348
std     227.335170    8.595740  1910.930790
min      20.000000    3.000000   300.000000
25%      50.000000    8.000000   800.000000
50%     100.000000   12.000000  1200.000000
75%     300.000000   20.000000  2400.000000
max    1200.000000   50.000000  7200.000000

## Check shape and columns

In [27]:
print("Shape:", df.shape)
print("Columns:", df.columns)

Shape: (369, 6)
Columns: Index(['date', 'product', 'category', 'price', 'quantity', 'revenue'], dtype='object')

## Check data types only

In [28]:
print(df.dtypes)

date         object
product      object
category     object
price       float64
quantity    float64
revenue     float64
dtype: object

## Check missing values

In [29]:
print(df.isnull().sum())

date        0
product     0
category    0
price       2
quantity    1
revenue     1
dtype: int64

## Drop missing rows

In [30]:
df.dropna(inplace=True)

In [31]:
df.isnull().sum()

date        0
product     0
category    0
price       0
quantity    0
revenue     0
dtype: int64

## Drop duplicates

In [32]:
df.drop_duplicates(inplace=True)

In [33]:
df.head()

         date     product     category   price  quantity  revenue
0  2022-01-01  Smartphone  Electronics   600.0      10.0   6000.0
1  2022-01-01      Laptop  Electronics  1200.0       5.0   6000.0
2  2022-01-02     T-Shirt     Clothing    20.0      50.0   1000.0
3  2022-01-03  Headphones  Electronics   100.0      20.0   2000.0
4  2022-01-04     T-Shirt     Clothing    20.0      25.0    500.0

## Value counts

In [34]:
print(df['category'].value_counts())

category
Electronics    129
Clothing       119
Accessories     67
Bags            23
Shoes           23
Clohting         1
Bgas             1
Shoeses          1
Name: count, dtype: int64

## Unique values

In [35]:
print(df['product'].unique())

['Smartphone' 'Laptop' 'T-Shirt' 'Headphones' 'Watch' 'Tablet' 'Coat'
 'Smartwatch' 'Speaker' 'Backpack' 'Hoodie' 'Sneakers' 'Wallet' 'Jeans']

In [36]:
print(df['category'].unique())

['Electronics' 'Clothing' 'Accessories' 'Bags' 'Shoes' 'Clohting' 'Bgas'
 'Shoeses']

In [42]:
df['category'] = df['category'].apply(lambda x : 'Bags' if x == 'Bgas' else
                                     'Clothing' if x == 'Clohting' else 
                                      'Shoes' if x== 'Shoeses' else x)

#### OR

In [49]:
df['category'] = df['category'].replace({
    'Clohting':'Clothing',
    'Shoeses': 'Shoes',
    'Bgas' : 'Bags'
})

In [44]:
df['category'].unique()

array(['Electronics', 'Clothing', 'Accessories', 'Bags', 'Shoes'],
      dtype=object)

In [48]:
df.groupby('category')['product'].unique()

category
Accessories                          [Watch, Smartwatch, Wallet]
Bags                                                  [Backpack]
Clothing                          [T-Shirt, Coat, Hoodie, Jeans]
Electronics    [Smartphone, Laptop, Headphones, Tablet, Speaker]
Shoes                                                 [Sneakers]
Name: product, dtype: object

In [48]:
df.groupby('category')['product'].unique()

category
Accessories                          [Watch, Smartwatch, Wallet]
Bags                                                  [Backpack]
Clothing                          [T-Shirt, Coat, Hoodie, Jeans]
Electronics    [Smartphone, Laptop, Headphones, Tablet, Speaker]
Shoes                                                 [Sneakers]
Name: product, dtype: object

## Apply function

In [32]:
df['price_with_tax'] = df['price'].apply(lambda x: x * 1.17)
df.head(3)

,date,product,category,price,quantity,revenue,price_with_tax
0,2022-01-01,Smartphone,Electronics,600.0,10.0,6000.0,702.0
1,2022-01-01,Laptop,Electronics,1200.0,5.0,6000.0,1404.0
2,2022-01-02,T-Shirt,Clothing,20.0,50.0,1000.0,23.4

# Sort by price

In [33]:
df.sort_values('price', ascending=False)

,date,product,category,price,quantity,revenue,price_with_tax
1,2022-01-01,Laptop,Electronics,1200.0,5.0,6000.0,1404.0
0,2022-01-01,Smartphone,Electronics,600.0,10.0,6000.0,702.0
87,2022-03-27,Smartphone,Electronics,600.0,9.0,5400.0,702.0
215,2022-08-02,Smartphone,Electronics,600.0,10.0,6000.0,702.0
107,2022-04-16,Smartphone,Electronics,600.0,6.0,3600.0,702.0
...,...,...,...,...,...,...,...
145,2022-05-24,T-Shirt,Clothing,20.0,15.0,300.0,23.4
295,2022-10-20,T-Shirt,Clothing,20.0,20.0,400.0,23.4
130,2022-05-09,T-Shirt,Clothing,20.0,30.0,600.0,23.4
115,2022-04-24,T-Shirt,Clothing,20.0,25.0,500.0,23.4
142,2022-05-21,T-Shirt,Clothing,20.0,25.0,500.0,23.4

## Group by category and find total revenue

In [34]:
print(df.groupby('category')['revenue'].sum())

category
Accessories    101400.0
Bags            19500.0
Bgas              900.0
Clohting         1200.0
Clothing        93150.0
Electronics    509480.0
Shoes           20640.0
Shoeses           960.0
Name: revenue, dtype: float64

## Multiple aggregations

In [50]:
print(df.groupby('category').agg({'price': ['mean', 'max', 'min'], 
                                  'revenue': 'sum', 'quantity': 'sum'}))

                  price                 revenue quantity
                   mean     max   min       sum      sum
category
Accessories  156.417910   200.0  30.0  101400.0    902.0
Bags          50.000000    50.0  50.0   20400.0    408.0
Clothing      53.166667   100.0  20.0   94350.0   2251.0
Electronics  439.534884  1200.0  80.0  509480.0   1439.0
Shoes         80.000000    80.0  80.0   21600.0    270.0

In [52]:
df[df['price'] <= 70]['category'].unique()

array(['Clothing', 'Bags', 'Accessories'], dtype=object)

In [53]:
df[df['price'] <= 70]['product'].unique()

array(['T-Shirt', 'Backpack', 'Hoodie', 'Wallet', 'Jeans'], dtype=object)

In [55]:
df[df['price'] <= 70]

           date   product     category  price  quantity  revenue
2    2022-01-02   T-Shirt     Clothing   20.0      50.0   1000.0
4    2022-01-04   T-Shirt     Clothing   20.0      25.0    500.0
11   2022-01-10  Backpack         Bags   50.0      20.0   1000.0
12   2022-01-11    Hoodie     Clothing   40.0      30.0   1200.0
15   2022-01-14    Wallet  Accessories   30.0      40.0   1200.0
..          ...       ...          ...    ...       ...      ...
355  2022-12-18  Backpack         Bags   50.0      15.0    750.0
356  2022-12-19   T-Shirt     Clothing   20.0      20.0    400.0
360  2022-12-23   T-Shirt     Clothing   20.0      25.0    500.0
362  2022-12-25     Jeans     Clothing   50.0      15.0    750.0
368  2022-12-31    Hoodie     Clothing   40.0      30.0   1200.0

[120 rows x 6 columns]

## Convert date into y-m-d  format

In [5]:
df['date'] = pd.to_datetime(df['date'])
# print(df['date'].dt.year)
# print(df['date'].dt.month)
df.head(8)

        date     product     category   price  quantity  revenue
0 2022-01-01  Smartphone  Electronics   600.0      10.0   6000.0
1 2022-01-01      Laptop  Electronics  1200.0       5.0   6000.0
2 2022-01-02     T-Shirt     Clothing    20.0      50.0   1000.0
3 2022-01-03  Headphones  Electronics   100.0      20.0   2000.0
4 2022-01-04     T-Shirt     Clothing    20.0      25.0    500.0
5 2022-01-05       Watch  Accessories   150.0      10.0   1500.0
6 2022-01-06  Smartphone  Electronics   600.0       8.0   4800.0
7 2022-01-06      Tablet  Electronics   400.0       5.0   2000.0

In [ ]:
# Select a single column
print(df['product'])

# Select multiple columns
print(df[['product', 'price']])

# Select a specific row by index
print(df.loc[1])

# Select by position
print(df.iloc[0, 2])   # Row 0, column 2 (category)

In [ ]:
# Add new column
df['discount'] = df['price'] * 0.10
print(df)

# Modify existing column
df['revenue'] = df['price'] * df['quantity']
print(df)

# Drop column
df.drop('discount', axis=1, inplace=True)
print(df)

# Rename columns
df.rename(columns={'product': 'item_name'}, inplace=True)
print(df)

In [ ]:
# Filter rows where price > 500
print(df[df['price'] > 500])

# Multiple conditions
print(df[(df['price'] > 100) & (df['category'] == 'Electronics')])

In [ ]:
# Save to CSV
df.to_csv('sales_data.csv', index=False)

# Read again
# new_df = pd.read_csv('sales_data.csv')
# print(new_df.head())