In [1]:
import numpy as np
import pandas as pd

In [12]:
df = pd.read_csv('C:\\Users\\Admin\\Desktop\\DataScience D3\\Product Sales Data.csv')
df.head()

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
0,Jan,5100,9600,1525,1550,1200,2510,21485,211500
1,Feb,5000,6500,1225,1250,2100,2640,18715,183800
2,Mar,4450,9950,1365,1390,3550,2150,22855,225200
3,Apr,5770,9270,1155,1180,1870,3410,22655,223200
4,May,4460,8160,1765,1790,1560,3610,21345,210100

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Month         12 non-null     object
 1   Cream         12 non-null     int64
 2   Detergent     12 non-null     int64
 3   Moisturizer   12 non-null     int64
 4   Sanitizer     12 non-null     int64
 5   Shampoo       12 non-null     int64
 6   Soap          12 non-null     int64
 7   Total Units   12 non-null     int64
 8   Total Profit  12 non-null     int64
dtypes: int64(8), object(1)
memory usage: 996.0+ bytes

In [14]:
df.describe()

,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
count,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000,12.000000
mean,5725.833333,9900.833333,1567.916667,1592.916667,2117.500000,2883.333333,23788.333333,260775.000000
std,1242.032486,2348.095779,316.733745,316.733745,617.724931,584.595172,3718.169964,70143.659404
min,4450.000000,6500.000000,1145.000000,1170.000000,1200.000000,2000.000000,18715.000000,183800.000000
25%,4762.500000,8415.000000,1330.000000,1355.000000,1795.000000,2470.000000,21295.000000,211150.000000
50%,5430.000000,9490.000000,1552.500000,1577.500000,1995.000000,2840.000000,22755.000000,229850.000000
75%,6300.000000,10445.000000,1790.000000,1815.000000,2325.000000,3445.000000,25937.500000,297175.000000
max,8200.000000,14800.000000,2125.000000,2150.000000,3550.000000,3710.000000,30405.000000,413300.000000

In [15]:
df.isnull()

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
5,False,False,False,False,False,False,False,False,False
6,False,False,False,False,False,False,False,False,False
7,False,False,False,False,False,False,False,False,False
8,False,False,False,False,False,False,False,False,False
9,False,False,False,False,False,False,False,False,False
10,False,False,False,False,False,False,False,False,False
11,False,False,False,False,False,False,False,False,False

In [16]:
df.isnull().sum()

Month           0
Cream           0
Detergent       0
Moisturizer     0
Sanitizer       0
Shampoo         0
Soap            0
Total Units     0
Total Profit    0
dtype: int64

In [17]:
df.dropna()

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
0,Jan,5100,9600,1525,1550,1200,2510,21485,211500
1,Feb,5000,6500,1225,1250,2100,2640,18715,183800
2,Mar,4450,9950,1365,1390,3550,2150,22855,225200
3,Apr,5770,9270,1155,1180,1870,3410,22655,223200
4,May,4460,8160,1765,1790,1560,3610,21345,210100
5,Jun,4790,7890,1580,1605,1890,2770,20525,201900
6,Jul,4680,9380,1145,1170,1780,2990,21145,296000
7,Aug,5760,10360,1425,1450,2860,3710,25565,361900
8,Sep,6000,8500,1805,1830,2100,3550,23785,234500
9,Oct,8200,10700,1915,1940,2300,2000,27055,267200
10,Nov,7200,13700,2125,2150,2400,2350,29925,413300
11,Dec,7300,14800,1785,1810,1800,2910,30405,300700

In [19]:
df[['Month', 'Total Units']]

   Month  Total Units
0    Jan        21485
1    Feb        18715
2    Mar        22855
3    Apr        22655
4    May        21345
5    Jun        20525
6    Jul        21145
7    Aug        25565
8    Sep        23785
9    Oct        27055
10   Nov        29925
11   Dec        30405

In [21]:
df[2:9]

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
2,Mar,4450,9950,1365,1390,3550,2150,22855,225200
3,Apr,5770,9270,1155,1180,1870,3410,22655,223200
4,May,4460,8160,1765,1790,1560,3610,21345,210100
5,Jun,4790,7890,1580,1605,1890,2770,20525,201900
6,Jul,4680,9380,1145,1170,1780,2990,21145,296000
7,Aug,5760,10360,1425,1450,2860,3710,25565,361900
8,Sep,6000,8500,1805,1830,2100,3550,23785,234500

In [22]:
df.loc[2:8]

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
2,Mar,4450,9950,1365,1390,3550,2150,22855,225200
3,Apr,5770,9270,1155,1180,1870,3410,22655,223200
4,May,4460,8160,1765,1790,1560,3610,21345,210100
5,Jun,4790,7890,1580,1605,1890,2770,20525,201900
6,Jul,4680,9380,1145,1170,1780,2990,21145,296000
7,Aug,5760,10360,1425,1450,2860,3710,25565,361900
8,Sep,6000,8500,1805,1830,2100,3550,23785,234500

In [23]:
df.iloc[2:8, 1:7]

   Cream  Detergent  Moisturizer  Sanitizer  Shampoo  Soap
2   4450       9950         1365       1390     3550  2150
3   5770       9270         1155       1180     1870  3410
4   4460       8160         1765       1790     1560  3610
5   4790       7890         1580       1605     1890  2770
6   4680       9380         1145       1170     1780  2990
7   5760      10360         1425       1450     2860  3710

In [25]:
df.loc[2:7, 'Cream':'Soap']

   Cream  Detergent  Moisturizer  Sanitizer  Shampoo  Soap
2   4450       9950         1365       1390     3550  2150
3   5770       9270         1155       1180     1870  3410
4   4460       8160         1765       1790     1560  3610
5   4790       7890         1580       1605     1890  2770
6   4680       9380         1145       1170     1780  2990
7   5760      10360         1425       1450     2860  3710

In [27]:
df[df['Cream'] > 4500]

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
0,Jan,5100,9600,1525,1550,1200,2510,21485,211500
1,Feb,5000,6500,1225,1250,2100,2640,18715,183800
3,Apr,5770,9270,1155,1180,1870,3410,22655,223200
5,Jun,4790,7890,1580,1605,1890,2770,20525,201900
6,Jul,4680,9380,1145,1170,1780,2990,21145,296000
7,Aug,5760,10360,1425,1450,2860,3710,25565,361900
8,Sep,6000,8500,1805,1830,2100,3550,23785,234500
9,Oct,8200,10700,1915,1940,2300,2000,27055,267200
10,Nov,7200,13700,2125,2150,2400,2350,29925,413300
11,Dec,7300,14800,1785,1810,1800,2910,30405,300700

In [28]:
df[df['Cream'] > 5000]

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
0,Jan,5100,9600,1525,1550,1200,2510,21485,211500
3,Apr,5770,9270,1155,1180,1870,3410,22655,223200
7,Aug,5760,10360,1425,1450,2860,3710,25565,361900
8,Sep,6000,8500,1805,1830,2100,3550,23785,234500
9,Oct,8200,10700,1915,1940,2300,2000,27055,267200
10,Nov,7200,13700,2125,2150,2400,2350,29925,413300
11,Dec,7300,14800,1785,1810,1800,2910,30405,300700

In [30]:
(df['Cream'] >5000 ) & (df['Sanitizer'] > 200)

0      True
1     False
2     False
3      True
4     False
5     False
6     False
7      True
8      True
9      True
10     True
11     True
dtype: bool

In [32]:
df[(df['Cream'] >5000 ) & (df['Sanitizer'] > 1500)]

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit
0,Jan,5100,9600,1525,1550,1200,2510,21485,211500
8,Sep,6000,8500,1805,1830,2100,3550,23785,234500
9,Oct,8200,10700,1915,1940,2300,2000,27055,267200
10,Nov,7200,13700,2125,2150,2400,2350,29925,413300
11,Dec,7300,14800,1785,1810,1800,2910,30405,300700

In [35]:
df['Products'] = df.loc[:, 'Cream':'Soap'].sum(axis=1)

In [36]:
df

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Units,Total Profit,Products
0,Jan,5100,9600,1525,1550,1200,2510,21485,211500,21485
1,Feb,5000,6500,1225,1250,2100,2640,18715,183800,18715
2,Mar,4450,9950,1365,1390,3550,2150,22855,225200,22855
3,Apr,5770,9270,1155,1180,1870,3410,22655,223200,22655
4,May,4460,8160,1765,1790,1560,3610,21345,210100,21345
5,Jun,4790,7890,1580,1605,1890,2770,20525,201900,20525
6,Jul,4680,9380,1145,1170,1780,2990,21145,296000,21145
7,Aug,5760,10360,1425,1450,2860,3710,25565,361900,25565
8,Sep,6000,8500,1805,1830,2100,3550,23785,234500,23785
9,Oct,8200,10700,1915,1940,2300,2000,27055,267200,27055
10,Nov,7200,13700,2125,2150,2400,2350,29925,413300,29925
11,Dec,7300,14800,1785,1810,1800,2910,30405,300700,30405

In [40]:
df.drop('Total Units', axis=1, inplace=True)

In [41]:
df.tail()

,Month,Cream,Detergent,Moisturizer,Sanitizer,Shampoo,Soap,Total Profit,Products
7,Aug,5760,10360,1425,1450,2860,3710,361900,25565
8,Sep,6000,8500,1805,1830,2100,3550,234500,23785
9,Oct,8200,10700,1915,1940,2300,2000,267200,27055
10,Nov,7200,13700,2125,2150,2400,2350,413300,29925
11,Dec,7300,14800,1785,1810,1800,2910,300700,30405