In [41]:
import pandas as pd
import seaborn as sns

!pip install seaborn

In [42]:
df  = sns.load_dataset('titanic')
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [43]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [44]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%      1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [45]:
df.columns

Index(['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'fare',
       'embarked', 'class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', 'alone'],
      dtype='object')

In [46]:
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [47]:
df['age'].fillna(df['age'].mean(), inplace=True)

In [37]:
# df['embarked'].fillna(df['embarked'].mode(), inplace=True)

In [48]:
from sklearn.impute import SimpleImputer
si= SimpleImputer(strategy='mean')
df['age'] = si.fit_transform(df[['age']])

In [55]:
si= SimpleImputer(strategy='most_frequent')
df[['embarked']] = si.fit_transform(df[['embarked']])

In [56]:
df[['embark_town']] = si.fit_transform(df[['embark_town']])

In [52]:
si= SimpleImputer(strategy='constant', fill_value=0)
df[['deck']] = si.fit_transform(df[['deck']])

In [57]:
df.isnull().sum()

survived       0
pclass         0
sex            0
age            0
sibsp          0
parch          0
fare           0
embarked       0
class          0
who            0
adult_male     0
deck           0
embark_town    0
alive          0
alone          0
dtype: int64

In [11]:
df.select_dtypes(include='number').columns

Index(['survived', 'pclass', 'age', 'sibsp', 'parch', 'fare'], dtype='object')

In [58]:
col = df.select_dtypes(include='number')
corr = col.corr()
corr

          survived    pclass       age     sibsp     parch      fare
survived  1.000000 -0.338481 -0.069809 -0.035322  0.081629  0.257307
pclass   -0.338481  1.000000 -0.331339  0.083081  0.018443 -0.549500
age      -0.069809 -0.331339  1.000000 -0.232625 -0.179191  0.091566
sibsp    -0.035322  0.083081 -0.232625  1.000000  0.414838  0.159651
parch     0.081629  0.018443 -0.179191  0.414838  1.000000  0.216225
fare      0.257307 -0.549500  0.091566  0.159651  0.216225  1.000000

In [60]:
df.describe()

         survived      pclass         age       sibsp       parch        fare
count  891.000000  891.000000  891.000000  891.000000  891.000000  891.000000
mean     0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std      0.486592    0.836071   13.002015    1.102743    0.806057   49.693429
min      0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%      0.000000    2.000000   22.000000    0.000000    0.000000    7.910400
50%      0.000000    3.000000   29.699118    0.000000    0.000000   14.454200
75%      1.000000    3.000000   35.000000    1.000000    0.000000   31.000000
max      1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [66]:
scaled = df.select_dtypes(include='number').columns

In [63]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
df[scaled] = scaler.fit_transform(df[scaled])

In [64]:
df.head(3)

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,-0.789272,0.827377,male,-0.592481,0.432793,-0.473674,-0.502445,S,Third,man,True,0,Southampton,no,False
1,1.266990,-1.566107,female,0.638789,0.432793,-0.473674,0.786845,C,First,woman,False,C,Cherbourg,yes,False
2,1.266990,0.827377,female,-0.284663,-0.474545,-0.473674,-0.488854,S,Third,woman,False,0,Southampton,yes,True

In [68]:
df.select_dtypes(include='object').head(2)

      sex embarked    who deck  embark_town alive
0    male        S    man    0  Southampton    no
1  female        C  woman    C    Cherbourg   yes

In [69]:
df.embarked.unique()

array(['S', 'C', 'Q'], dtype=object)

## Encoding
##### Convertiong Categorical columns into numbers

In [70]:
df['alive'] = df['alive'].map({'yes':1, 'no':0})

In [71]:
from sklearn.preprocessing import LabelEncoder, OrdinalEncoder, OneHotEncoder
le = LabelEncoder()
df['sex'] = le.fit_transform(df['sex'])

In [ ]:
df['embarked'] = le.fit_transform(df['embarked'])

In [75]:
df['who'] = le.fit_transform(df['who'])
df['embark_town'] = le.fit_transform(df['embark_town'])

In [79]:
df['class'] = le.fit_transform(df['class'])

In [76]:
df.deck.unique()

array([0, 'C', 'E', 'G', 'D', 'A', 'B', 'F'], dtype=object)

In [77]:
df['deck'] = df['deck'].map({'A':1,'B':2, 'C':3, 
                             'D':4, 'E':5,'F':6, 'G':7})

In [80]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,-0.789272,0.827377,1,-0.592481,0.432793,-0.473674,-0.502445,2,2,1,True,NaN,2,0,False
1,1.266990,-1.566107,0,0.638789,0.432793,-0.473674,0.786845,0,0,2,False,3.0,0,1,False
2,1.266990,0.827377,0,-0.284663,-0.474545,-0.473674,-0.488854,2,2,2,False,NaN,2,1,True
3,1.266990,-1.566107,0,0.407926,0.432793,-0.473674,0.420730,2,0,2,False,3.0,2,1,False
4,-0.789272,0.827377,1,0.407926,-0.474545,-0.473674,-0.486337,2,2,1,True,NaN,2,0,True

In [81]:
x = df.drop('alive', axis=1)
y = df['alive']

# Split Data into Training and Testing

In [83]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,
                                            test_size=0.2,
                                            random_state=42 )

In [85]:
x_train.shape

(712, 14)

In [87]:
x_test.shape

(179, 14)